// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fclvgudstgvzsbyoephp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZjbHZndWRzdGd2enNieW9lcGhwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgyMTg5ODQsImV4cCI6MjA3Mzc5NDk4NH0.j3l_YwO_1mxLkl7529JbJI5GWQh5ks8dJ299UNpywcU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});